version: "3"

services:

  nginx:
    image: nginx
    volumes:
      #public
      - ./www:/var/www/html
      #configs
      - ./docker/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/configs/hosts:/etc/hosts
      #user
      - ./docker/nginx/configs/www.conf:/usr/local/etc/php-fpm.d/www.conf
      #logs
      - ./docker/nginx/logs:/var/log/nginx

    ports:
      - "80:80"

  php:
    build: ./docker/php
    volumes:
      #public
      - ./www:/var/www/html
      #configs
      - ./docker/php/configs/php.ini:/usr/local/etc/php/php.ini
      

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
