version: "2"

services:
  php-apache:
    build: ./docker/phpApache
    volumes:
      # public
      - ./www:/var/www/html
      # configs
      - ./docker/phpApache/configs/php.ini:/usr/local/etc/php/php.ini
      # logs
      - ./docker/phpApache/logs:/var/log/apache2
      # configs
      - ./docker/phpApache/configs/sites-available:/etc/apache2/sites-available
    ports:
      - "80:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
