version: "3"

services:
  app:
    build:
      context: ./docker/app
      args:
        - USER_ID 
        - GROUP_ID

    volumes:
      # public
      - ./www:/var/www/html
      # configs
      - ./docker/app/configs/php.ini:/usr/local/etc/php/php.ini
      - ./docker/app/configs/sites-available:/etc/apache2/sites-available
      # hosts
      - ./docker/app/configs/hosts:/etc/hosts
      # logs
      - ./docker/app/logs:/var/log/apache2
    ports:
      - "80:80"

    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # db
      - ./docker/db/mysql:/var/lib/mysql
      # configs
      - ./docker/db/configs/my.cnf:/etc/mysql/my.cnf

    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
